services:
  oase-kms:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=development
      - RAILS_MAX_THREADS=5
      - RAILS_MASTER_KEY=
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:notsosecret@oase-postgres:5432/key_store
    ports:
      - "3002:3002"
  oase-postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=notsosecret
    ports:
      - 5432:5432