networks:
  oase-network:

services:
  oase-kms:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=development
      - RAILS_MAX_THREADS=5
      - RAILS_MASTER_KEY=
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:verysecret@oase-postgres:5433/key_store
    ports:
      - "3002:3002"
    networks:
      - oase-network
  oase-postgres-kms:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=verysecret
      - POSTGRES_PORT=5433
    ports:
      - 5433:5433
    networks:
      - oase-network