services:
  oase-kms:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:notsosecret@oase-postgres:5432/key_store_test
    ports:
      - "3000:3000"
  oase-postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=notsosecret
    ports:
      - 5432:5432