name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: "0.1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: git config --global url.https://$ORG_GITHUB_TOKEN@github.com/.insteadOf https://github.com/
      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: docker-compose.yaml
          up-flags: "--build"
          down-flags: "--volumes"
